on:
  workflow_dispatch:
  push:
    branches: main

- name: Render Quarto Project
  uses: quarto-dev/quarto-actions/render@v2
  with:
    to: html # If set, it will be equivalent to `quarto render --to html`
    path: docs # By default, the current working dir is used i.e `quarto render .`
