---
#title: "events"

page-layout: full
title-block-banner: false
knitr:
  opts_chunk: 
    collapse: true
execute: 
  echo: false
toc: true
---

# [EVENTS]{.third-color}

This is a non-exhaustive list of activities and events I have developed, including conferences, lectures, workshops and courses.

# Organization

I organized several editions of the [Brazilian Conference on Data Journalism and Digital Methods (Coda.Br)](https://escoladedados.org/coda/) from 2018 to 2022, including the first regional meeting in the Amazon region. Previously, I collaborated with [Witness](https://witness.org/) to organize the first national meeting on deepfakes and developed a series of events about free culture and piracy (Copyfight).

Belém, Brazil, 2022. [**Coda Amazônia**](https://escoladedados.org/coda/coda-amazonia/). 1 ed.

Online, 2021. [**Coda.Br - Conferência de Jornalismo de Dados e Métodos Digitais**](https://escoladedados.org/coda/coda2021/). 6 ed.

Online, 2020. [**Coda.Br - Conferência de Jornalismo de Dados e Métodos Digitais**](https://escoladedados.org/coda/coda2020/). 5 ed.

São Paulo, 2019. [**Deepfakes - prepare-se agora**](https://lab.witness.org/brasil-deepfakes-prepara-se-agora/). 1 ed.

São Paulo, 2019. [**Coda.Br - Conferência de Jornalismo de Dados e Métodos Digitais**](https://escoladedados.org/coda/coda2019/). 4 ed.

São Paulo, 2018. [**Coda.Br - Conferência de Jornalismo de Dados e Métodos Digitais**](https://escoladedados.org/coda/coda2018/). 3 ed.

Rio de Janeiro, 2014. **Copyfight**. 3 ed.

Rio de Janeiro, 2012. **Communication Laboratory at the Peoples Summit Rio+20**. 1 ed.

Rio de Janeiro, 2011. **Copyfight**. 2 ed.

Rio de Janeiro, 2010. **Copyfight**. 1 ed.

# Talks and lectures

Bergen, Norway, 2025. The 28th ACM SIGCHI Conference on Computer-Supported Cooperative Work & Social Computing (CSCW). [**Into the Crossfire: Evaluating the Use of a Language Model to Crowdsource Gun Violence Reports**](https://belisario.website/crossfire_paper)

Niterói, Brazil, 2025. Association of Internet Researchers Conference. **Cross-platform gendertrolling: a case study on a prominent harassment case in Brazil**.

Berlin, Germany, 2024. Global Innovation Gathering Weekend. **Way beyond ChatGPT: leveraging open source language models**.

Berlin, Germany, 2024. re:publica 2024. [**From Laughs to Courts: Multifaceted Uses of AI in the Global South**](https://re-publica.com/de/session/laughs-courts-multifaceted-uses-ai-global-south).

Berlin, Germany, 2024. Disinfo Demasked/DW Akademy. [**AI uses for fact-checking in Brazil**](https://belisards.github.io/slides-bert-fact-checking/).

Online, 2021. RightsCon. [**Anatomy of a visual investigation**](https://visualinvestigations.netlify.app/).

Salvador, Brazil, 2019. Simpósio LAVITS 2019. [**Expulsão/Exceção: arquitetura forense, conflito e direitos humanos**](https://medialabufrj.net/blog/2019/06/dobras-35-medialab-ufrj-no-simposio-lavits-2019/).

Rio de Janeiro, Brazil, 2019. Hackfest/Ministério Público do Estado do Rio de Janeiro. [**Dados abertos e transformação social**](https://www.mprj.mp.br/documents/20184/540394/palestras_hackfest.pdf).

São Paulo, Brazil, 2019. Campus Party. **Jornalismo de dados no Brasil**.

Viçosa, Brazil, 2019. Semana Acadêmica da Universidade Federal de Viçosa. **Jornalismo de dados no Brasil**.

Berlin, Germany, 2017. Re:Publica. **Coolab - Community networks in Brazil**.

Buenos Aires, Argentina, 2015. LAVITS. **III Simpósio Internacional da Rede Latinoamericana de Vigilância, Tecnologia e Sociedade**. Paper presentation.

Rio de Janeiro, Brazil, 2015. Ministério da Cultura. **[Diálogos em rede](https://rubi.casaruibarbosa.gov.br/bitstream/handle/20.500.11997/8797/Participa%C3%A7%C3%A3o%20social%20%C3%A9%20estimulada%20durante%20Di%C3%A1logos%20em%20Rede%20no%20Rio%20de%20Janeiro%20%E2%80%93%20Di%C3%A1logos%20em%20Rede.pdf?sequence=1&isAllowed=y)**.

Duque de Caxias, Brazil, 2015. **Território Baixada.Web, Ficção, Relato e Amor: cartografia e resistências**.

Berlin, Germany, 2014. Transmediale. **Micropolitics of the Post-Digital: From street protests to transitional spaces in Brazil**.

Geneva, Switzerland, 2013. Open Knowledge Conference, **Data driven campaigning**.

Recife, Brazil, 2012. III Semana Chico Science. **Banditismo por uma questão de classe: música e hacktivismo na cultura contemporânea**.

Rio de Janeiro, Brazil, 2007. Undergraduate research seminar. **Do cineclubismo enquanto prática de comunicação comunitária**.

# Labs

Madrid, Spain, 2017. Visualizar17 - Medialab Prado. **Agrega.la**.

Cartagena, Colombia, 2016. Laboratório Iberoamericano de Inovação Cidadã. **Agrega.la**.

Mexico city, Mexico, 2016. **Openlabs - Caixa Mágica: dispositivo para participação social**.

# Workshops

São Paulo, Brazil, 2025. ABRAJI - Brazilian Conference on Investigative Journalism. [**Classificação de textos e imagens com IA de código-aberto**](https://belisario.website/classificacao_ia/)

Brasília, Brazil, 2024. América Aberta/Coda.Br. [**Texto, áudio e imagens: usando modelos de IA gratuitos e de código-aberto com dados não-estruturados**](https://bit.ly/ia-coda-24/)**.

Online, 2024. The Rory Peck Trust. [**Segurança digital para jornalistas**](https://bit.ly/sdigital-rorypeck).

São Paulo, Brazil, 2023. Coda.Br. [**Entendendo e usando Transformers, a tecnologia por trás do ChatGPT**](https://escoladedados.org/coda/coda2023/entendendo-e-usando-transformers-a-tecnologia-por-tras-do-chatgpt/)**.**

Geneva, Switzerland, 2023. European Data and Computational Journalism Conference. [**Beyond the hype: an introduction to NLP and language models**](https://github.com/belisards/intro_nlp_ddj)**.**

São Paulo, Brazil, 2019. Curso do Centro de Pesquisa e Formação do SESC-SP. **Espectro livre e redes comunitárias**.

Belém, Brazil, 2018. Seminário Amazônia Interconectada. **Narrativas e dados**.

Rio de Janeiro, Brazil, 2016. Encontro Nacional de Artes Cênicas do SESC. **Redes e Culturas Colaborativas**.

Quito, Ecuador, 2013. I Congreso Internacional de Cultura Viva y Comunitaria. **Taller de software libre**. 

Rio de Janeiro, Brazil, 2012. GNUGRAF. **Copyfight : Muito além do download grátis**.

Dakar, Senegal, 2011. World Social Forum. **Mandala: uma proposta de agregação de conteúdo para a mídia independente**.

